2403
vatsimhk/Hong-Kong-Sector-Package pull request #62
Opened 2024-03-24 19:10 UTC by EightSmart

2024-03-24 19:21 UTC, Syntax505 approved these changes
gud

2024-03-26 12:30 UTC, Syntax505 requested changes

2024-03-26 12:30 UTC, Syntax505 commented on Data/Sector/Hong-Kong-Sector-File.ese
>  COORD:N019.49.12.585:E113.58.42.622
This coordinate seems to be out of place?

2024-03-26 12:30 UTC, Syntax505 commented on Data/Sector/Hong-Kong-Sector-File.ese
>  COORD:N019.49.12.585:E113.58.42.622
wasn't highlighted correctly for some reason, specifically line 1731

2024-03-26 14:17 UTC, Syntax505 approved these changes

2024-04-02 16:34 UTC, UraniumLover approved these changes
ok thx

2024-04-02 16:40 UTC, merged